### Numpy 연습문제3

In [1]:
import numpy as np

### 연습문제. 마스크 인덱싱

In [2]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo',
                  'Park','Beomwoo'])
data = np.random.randn(8,4)  # 표준정규분포난수

In [3]:
data

array([[ 0.88991202, -0.82122873, -1.69926895, -1.59322334],
       [-1.95861691,  1.7561287 ,  1.7460879 , -1.54313157],
       [ 0.46845382, -0.56811188, -0.38114702,  1.63941818],
       [-2.72704556,  0.18998193,  1.18380743,  1.04611969],
       [-0.37483315, -0.39112471, -0.0493193 , -0.03187678],
       [-0.34693989, -1.00278447, -0.05098577, -0.47282007],
       [-0.15867397, -0.35226966, -1.073652  ,  0.69694457],
       [ 1.47488813, -0.07063946,  1.14670875, -1.56392331]])

#### 문제1. data array에서 0번째 열이 0보다 작은 행 데이터 가져오기

In [7]:
mask = data[:, 0] < 0
data[mask]
# data[mask,:]

array([[-1.95861691,  1.7561287 ,  1.7460879 , -1.54313157],
       [-2.72704556,  0.18998193,  1.18380743,  1.04611969],
       [-0.37483315, -0.39112471, -0.0493193 , -0.03187678],
       [-0.34693989, -1.00278447, -0.05098577, -0.47282007],
       [-0.15867397, -0.35226966, -1.073652  ,  0.69694457]])

#### 문제2. data array에서 0번째 열이 0보다 작은 행의 2, 3번째 열 데이터 가져오기

In [8]:
mask = data[:, 0] < 0
data[mask, 2:4]

array([[ 1.7460879 , -1.54313157],
       [ 1.18380743,  1.04611969],
       [-0.0493193 , -0.03187678],
       [-0.05098577, -0.47282007],
       [-1.073652  ,  0.69694457]])

----------------------------------------------

### 연습문제: 정렬

In [9]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

#### 문제1. 위 행렬에서 성적의 오름차순으로 학생의 이름을 출력하시오.

In [10]:
mask = np.argsort(score_array)
mask

array([0, 2, 4, 1, 3])

In [11]:
name_array[mask]

array(['John', 'Sarah', 'Samuel', 'Mike', 'Kate'], dtype='<U6')

#### 문제2. 성적이 가장 좋은 사람의 이름을 출력하시오

In [12]:
name_array[np.argmax(score_array)]

np.str_('Kate')