## Numpy 연습문제1

#### 1. np이름으로 numpy 패키지 가져오기

In [1]:
import numpy as np

#### 2. numpy 버전 출력하기

In [2]:
np.__version__

'2.2.4'

#### 3. 모두 0의 값을 갖는 사이즈가 10인 벡터 생성하기

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. 값 10~49를 갖는 벡터 생성하기

In [4]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5. 0~8 사이의 정수 값을 3X3 크기로 갖는 행렬 생성하기 

In [4]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. 실수 난수를 3X3X3의 크기로 갖는 배열 생성하기

In [7]:
np.random.rand(3,3,3)

array([[[0.42612723, 0.83367487, 0.20530785],
        [0.73117096, 0.72273679, 0.37493263],
        [0.3989756 , 0.28627556, 0.52995699]],

       [[0.39057906, 0.75552881, 0.55129072],
        [0.78217392, 0.50292889, 0.97089236],
        [0.36643383, 0.11197918, 0.6563597 ]],

       [[0.30206676, 0.68964243, 0.2015672 ],
        [0.82857284, 0.93345655, 0.16021727],
        [0.52515804, 0.45723715, 0.42993155]]])